### ISSUE TITLE
More Content Types

### ISSUE THREAD

**Issue by ChrisMcKenzie** [ChrisMcKenzie/accord#1]
Currently body in response and request only supports text/plain and application/json it would nice to support application/xml, and maybe a few others. not sure what those might be but if we build a nice interface for this conversion it should be trivial to add as many as we want

**Comment by ChrisMcKenzie** [comment]
@schambers I have moved that repo over to here.

**Comment by erbesharat** [comment]
I can take a look at the code and start working on it. But it's gonna take a little time from me to get familiar with the code. so if someone found a solution before me I would be happy to take a look.

**Comment by ghost** [comment]
You can go ahead. There's a couple of other issues I was going to look at.

**Comment by ChrisMcKenzie** [comment]
if you are curious where this happens, https://github.com/ChrisMcKenzie/accord/blob/master/cmd/test.go#L124

Perhaps this should be an interface that each type can implement.
